version: "3.8"

services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/work

  web:
    image: nginx:latest
    ports:
      - 10081:80
    volumes:
      - ./src:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:8.2
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    command: --sql-mode=NO_ENGINE_SUBSTITUTION
    ports:
      - 33060:3306

volumes:
  db-store: